---
- name: Remove swapfile from /etc/fstab
  mount:
    name: "Remove SWAP"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
